-- Optional seed data for a dev database: `pnpm db:migrate --seed`.
--
-- Intentionally empty: this platform ships with no sample/demo rows. A fresh
-- database starts blank and is filled through the panel (create a site, add
-- products, set hero/branding). Add throwaway fixtures below only for local
-- experiments — never brand or author placeholders.
