-- Preview source 'excerpt': preview_url holds an EPUB generated by cutting the
-- deliverable (story_epub_url) down to the first N% of its prose. It is a real,
-- separate file in the public bucket — the withheld chapters are not in it — so
-- the serve path is identical to 'epub'. The difference is only how it got there.
alter table public.lp_landing_pages
  drop constraint if exists lp_landing_pages_preview_type_check;
alter table public.lp_landing_pages
  add constraint lp_landing_pages_preview_type_check
  check (preview_type in ('html', 'pdf', 'link', 'epub', 'deliverable', 'excerpt'));

-- How much of the book to withhold, kept per product so regenerating after an
-- edit reproduces the same cut without the seller re-choosing it.
alter table public.lp_landing_pages
  add column if not exists preview_cut_percent smallint not null default 60;

alter table public.lp_landing_pages
  drop constraint if exists lp_landing_pages_preview_cut_percent_check;
alter table public.lp_landing_pages
  add constraint lp_landing_pages_preview_cut_percent_check
  check (preview_cut_percent between 5 and 95);
